
// ********RoostGPT********
/*

# Test generated by RoostGPT for test karate-vtal-appointment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /appointment_post for http method type POST 
# RoostTestHash=b7eaf9bc25
# 
# 

roost_feedback [6/5/2024, 10:59:14 AM]:Rectify this error 

extraneous input \n      \n      {\n        control: {\n          type: E,\n          code: 401,\n          message: Priorização de agendamento não autorizado\n        }\n      }\n       expecting {<EOF>, SCENARIO, SCENARIO_OUTLINE, TAGS, NEWLINE}
*/

// ********RoostGPT********


# Test generated by RoostGPT for test karate-vtal-appointment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /appointment_post for http method type POST 
# RoostTestHash=b7eaf9bc25
# 
# 

Feature: Post Appointment API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * configure headers = { 'Authorization': '#(karate.properties["AUTH_TOKEN"])' }

  Scenario: Create a new appointment successfully
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 201
    And match response ==
      """
      {
        "order": {
          "type": "#string",
          "associatedDocument": "#string",
          "addressChange": {
            "flag": "#boolean"
          }
        },
        "customer": {
          "subscriberId": "#string"
        },
        "appointment": {
          "id": "#string",
          "startDate": "#string",
          "finishDate": "#string",
          "priority": {
            "flag": "#boolean",
            "reason": "#string"
          }
        },
        "address": {
          "id": "#number"
        },
        "products": {
          "product": [
            {
              "type": "#string"
            }
          ]
        },
        "control": {
          "type": "S",
          "code": 201,
          "message": "Created"
        }
      }
      """

  Scenario: Bad Request - Invalid request body
    Given path '/appointment'
    And request
      """
      {
        "invalid": "request body"
      }
      """
    When method POST
    Then status 400
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 400,
          "message": "Bad Request"
        }
      }
      """

  Scenario: Unauthorized - Missing or invalid authorization token
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    And configure headers = { 'Authorization': 'invalid_token' }
    When method POST
    Then status 401
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 401,
          "message": "Unauthorized"
        }
      }
      """

  Scenario: Forbidden - Scope Not Permitted
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 403
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 403,
          "message": "Forbidden - Scope Not Permitted"
        }
      }
      """

  Scenario: Not Found - Invalid slot ID
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "invalid_slot_id"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 404
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 404,
          "message": "Identificador do Slot não encontrado ou expirado"
        }
      }
      """

  Scenario: Not Acceptable - Unsupported request
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 406
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 406,
          "message": "Not Acceptable"
        }
      }
      """

  Scenario: Precondition Failed
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 412
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 412,
          "message": "Precondition Failed"
        }
      }
      """

  Scenario: Locked - Appointment cannot be changed
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 423
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 423,
          "message": "Agendamento não pode ser alterado"
        }
      }
      """

  Scenario: Too Many Requests - Exceeded Quota
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 429
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 429,
          "message": "Too Many Requests - Exceeded Quota"
        }
      }
      """

  Scenario: Internal Server Error
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 500
    And match response ==
      """
      {
        "control": {
          "type": "T",
          "code": 500,
          "message": "Internal Server Error"
        }
      }
      """

  Scenario: Service Unavailable
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 503
    And match response ==
      """
      {
        "control": {
          "type": "T",
          "code": 503,
          "message": "Service Unavailable"
        }
      }
      """

  Scenario: Gateway Timeout
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra"
        }
      }
      """
    When method POST
    Then status 504
    And match response ==
      """
      {
        "control": {
          "type": "T",
          "code": 504,
          "message": "Gateway Timeout"
        }
      }
      """

  Scenario: Unauthorized - Appointment prioritization not allowed
    Given path '/appointment'
    And request
      """
      {
        "appointment": {
          "slot": {
            "id": "bff13821-73c3-42cc-9327-b05c7df5a67f"
          },
          "reason": "Agendamento para Instalação de Fibra",
          "priority": {
            "flag": true,
            "reason": "Prioridade não autorizada"
          }
        }
      }
      """
    When method POST
    Then status 401
    And match response ==
      """
      {
        "control": {
          "type": "E",
          "code": 401,
          "message": "Priorização de agendamento não autorizado"
        }
      }
      """
