# ********RoostGPT********

# Test generated by RoostGPT for test karate-vtal-appointment using AI Type Claude AI and AI Model claude-3-opus-20240229
# 
# Feature file generated for /searchTimeSlot_get for http method type GET 
# RoostTestHash=0e2f009f7e
# 
# 

# ********RoostGPT********
Feature: Search Time Slot API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  Scenario Outline: Retrieve Search Time Slot
    Given path '/searchTimeSlot'
    And header Authorization = 'Bearer ' + authToken
    And param addressId = <addressId>
    And param subscriberId = <subscriberId>
    And param associatedDocument = <associatedDocument>
    And param startDate = <startDate>
    And param finishDate = <finishDate>
    And param orderType = <orderType>
    And param addressChangeFlag = <addressChangeFlag>
    And param productType = <productType>
    And param priorityFlag = <priorityFlag>
    And param priorityReason = <priorityReason>
    When method GET
    Then status <statusCode>
    And match response.control.type == <responseType>
    And match response.control.code == <responseCode>
    And match response.control.message contains <responseMessage>
    And match response.slots == '#[]'

    Examples:
      | read('searchTimeSlot_get.csv') |

  Scenario: Too Many Requests
    Given path '/searchTimeSlot'
    And header Authorization = 'Bearer ' + authToken
    And param addressId = 17713
    And param subscriberId = "VTAL001"
    And param associatedDocument = "VTT001"
    And param startDate = "2021-05-21T13:00:00"
    And param finishDate = "2021-06-04T13:00:00"
    And param orderType = "Instalacao"
    And param addressChangeFlag = true
    And param productType = "Banda Larga"
    And param priorityFlag = true
    And param priorityReason = "Cliente Diamond"
    When method GET
    Then status 429
    And match response.control.type == "E"
    And match response.control.code == 429
    And match response.control.message == "Too Many Requests - Exceeded Quota"

  Scenario: Internal Server Error
    Given path '/searchTimeSlot'
    And header Authorization = 'Bearer ' + authToken
    And param addressId = 17713
    And param subscriberId = "VTAL001"
    And param associatedDocument = "VTT001"
    And param startDate = "2021-05-21T13:00:00"
    And param finishDate = "2021-06-04T13:00:00"
    And param orderType = "Instalacao"
    And param addressChangeFlag = true
    And param productType = "Banda Larga"
    And param priorityFlag = true
    And param priorityReason = "Cliente Diamond"
    When method GET
    Then status 500
    And match response.control.type == "T"
    And match response.control.code == 500
    And match response.control.message == "Internal Server Error"

  Scenario: Service Unavailable
    Given path '/searchTimeSlot'
    And header Authorization = 'Bearer ' + authToken
    And param addressId = 17713
    And param subscriberId = "VTAL001"
    And param associatedDocument = "VTT001"
    And param startDate = "2021-05-21T13:00:00"
    And param finishDate = "2021-06-04T13:00:00"
    And param orderType = "Instalacao"
    And param addressChangeFlag = true
    And param productType = "Banda Larga"
    And param priorityFlag = true
    And param priorityReason = "Cliente Diamond"
    When method GET
    Then status 503
    And match response.control.type == "T"
    And match response.control.code == 503
    And match response.control.message == "Service Unavailable"

  Scenario: Gateway Timeout
    Given path '/searchTimeSlot'
    And header Authorization = 'Bearer ' + authToken
    And param addressId = 17713
    And param subscriberId = "VTAL001"
    And param associatedDocument = "VTT001"
    And param startDate = "2021-05-21T13:00:00"
    And param finishDate = "2021-06-04T13:00:00"
    And param orderType = "Instalacao"
    And param addressChangeFlag = true
    And param productType = "Banda Larga"
    And param priorityFlag = true
    And param priorityReason = "Cliente Diamond"
    When method GET
    Then status 504
    And match response.control.type == "T"
    And match response.control.code == 504
    And match response.control.message == "Gateway Timeout"
